/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JPanel;
import Method.DaftarMenu;
import Method.Makanan;
import java.util.ArrayList;

/**
 *
 * @author Kelompok 5
 */
public class Recommendation extends javax.swing.JFrame {

    static DaftarMenu menu = new DaftarMenu();
    static ArrayList<Makanan> rekom = new ArrayList<>();
    /**
     * Creates new form Recommendation
     */
    public Recommendation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ynMakanan = new javax.swing.ButtonGroup();
        shtMakanan = new javax.swing.ButtonGroup();
        sizeMinuman = new javax.swing.ButtonGroup();
        ynEs = new javax.swing.ButtonGroup();
        ynKafein = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choose = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        layerMakanan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manis = new javax.swing.JCheckBox();
        asam = new javax.swing.JCheckBox();
        asin = new javax.swing.JCheckBox();
        pedas = new javax.swing.JCheckBox();
        gurih = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        mknMoney = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vegan = new javax.swing.JRadioButton();
        nonVegan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        healtyF = new javax.swing.JRadioButton();
        junkF = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        negaraMkn = new javax.swing.JComboBox<>();
        layerMinuman = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        mnumMoney = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        negaraMnum = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rekomendasi");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(800, 800));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Silahkan pilih:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 45, 160, 20));

        choose.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        bg.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 76, 149, -1));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        layerMakanan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Pilih rasa yang anda inginkan:");

        manis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        manis.setText("Manis");
        manis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manisActionPerformed(evt);
            }
        });

        asam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        asam.setText("Asam");
        asam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asamActionPerformed(evt);
            }
        });

        asin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        asin.setText("Asin");
        asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asinActionPerformed(evt);
            }
        });

        pedas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pedas.setText("Pedas");
        pedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedasActionPerformed(evt);
            }
        });

        gurih.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gurih.setText("Gurih");
        gurih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gurihActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Jumlah uang yang anda miliki:");

        mknMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mknMoneyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Apakah anda seorang vegetarian?");

        ynMakanan.add(vegan);
        vegan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vegan.setText("Ya");
        vegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veganActionPerformed(evt);
            }
        });

        ynMakanan.add(nonVegan);
        nonVegan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nonVegan.setText("Tidak");
        nonVegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonVeganActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Pilih tipe makanan yang anda sukai:");

        shtMakanan.add(healtyF);
        healtyF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        healtyF.setText("Healthy Food");
        healtyF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healtyFActionPerformed(evt);
            }
        });

        shtMakanan.add(junkF);
        junkF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        junkF.setText("Junk Food");
        junkF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                junkFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Pilih asal negara produk:");

        negaraMkn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        negaraMkn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tampilkan Semua", "China", "Indonesia", "Italia", "Mesir" }));
        negaraMkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaraMknActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerMakananLayout = new javax.swing.GroupLayout(layerMakanan);
        layerMakanan.setLayout(layerMakananLayout);
        layerMakananLayout.setHorizontalGroup(
            layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerMakananLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerMakananLayout.createSequentialGroup()
                        .addComponent(manis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(asam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(asin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pedas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gurih, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layerMakananLayout.createSequentialGroup()
                        .addComponent(healtyF)
                        .addGap(18, 18, 18)
                        .addComponent(junkF))
                    .addGroup(layerMakananLayout.createSequentialGroup()
                        .addComponent(vegan)
                        .addGap(18, 18, 18)
                        .addComponent(nonVegan))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mknMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negaraMkn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layerMakananLayout.setVerticalGroup(
            layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerMakananLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manis)
                    .addComponent(asam)
                    .addComponent(asin)
                    .addComponent(pedas)
                    .addComponent(gurih))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mknMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegan)
                    .addComponent(nonVegan))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layerMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healtyF)
                    .addComponent(junkF))
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(negaraMkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLayeredPane1.add(layerMakanan, "card2");

        layerMinuman.setBackground(new java.awt.Color(153, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Pilih rasa yang anda inginkan:");

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox7.setText("Manis");

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox8.setText("Asam");

        jCheckBox9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox9.setText("Asin");

        jCheckBox10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox10.setText("Pahit");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Jumlah uang yang anda miliki:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Pilih ukuran minuman:");

        sizeMinuman.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton1.setText("Kecil");

        sizeMinuman.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton2.setText("Sedang");

        sizeMinuman.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton3.setText("Besar");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Tambahkan es?");

        ynEs.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton4.setText("Boleh");

        ynEs.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton5.setText("Hangat Saja");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Mengandung kafein?");

        ynKafein.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton6.setText("Ya");

        ynKafein.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton11.setText("Tidak");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Pilih asal negara produk:");

        negaraMnum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        negaraMnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tampilkan Semua", "Jepang", "Malaysia", "Thailand" }));
        negaraMnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaraMnumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerMinumanLayout = new javax.swing.GroupLayout(layerMinuman);
        layerMinuman.setLayout(layerMinumanLayout);
        layerMinumanLayout.setHorizontalGroup(
            layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerMinumanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(negaraMnum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layerMinumanLayout.createSequentialGroup()
                        .addComponent(jRadioButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton11))
                    .addGroup(layerMinumanLayout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5))
                    .addGroup(layerMinumanLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnumMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layerMinumanLayout.createSequentialGroup()
                        .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layerMinumanLayout.setVerticalGroup(
            layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerMinumanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mnumMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(negaraMnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLayeredPane1.add(layerMinuman, "card3");

        bg.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 123, -1, 489));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Cek Rekomendasi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 657, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText(">");
        jButton4.setToolTipText("click to get recommendation");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 760, 30, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<");
        jButton5.setToolTipText("click to get recommendation");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        bg.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\GitHub\\Project_Kel5\\src\\main\\java\\Images\\bg.jpg")); // NOI18N
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        // TODO add your handling code here:
        if(choose.getSelectedItem().equals("Makanan")) {
            switchPane(layerMakanan);
        } else {
            switchPane(layerMinuman);
        }
    }//GEN-LAST:event_chooseActionPerformed

    private void junkFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_junkFActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        int loop = rekom.size();
        int i = 0;
        while(i <= loop) {
            if(rekom.get(i).getHealty()) {
            rekom.remove(i);
            loop = rekom.size();
            i = 0;
            } else {
            i++;
            }
        }
    }//GEN-LAST:event_junkFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Output out = new Output();
        String pmbuka = "Berikut makanan yang kami rekomendasikan: \n";
        if(choose.getSelectedItem().equals("Makanan")) {
        int jlh = rekom.size();
        if (jlh == 1) {
            out.setTeks(pmbuka +
                        rekom.get(0).getNama());
        } else if (jlh == 2) {
            out.setTeks(pmbuka +
                        rekom.get(0).getNama() + "\n" +
                        rekom.get(1).getNama());
        } else if (jlh == 3) {
            out.setTeks(pmbuka +
                        rekom.get(0).getNama() + "\n" +
                        rekom.get(1).getNama() + "\n" + 
                        rekom.get(2).getNama());
        } else if (jlh == 4) {
            out.setTeks(pmbuka +
                        rekom.get(0).getNama() + "\n" +
                        rekom.get(1).getNama() + "\n" +
                        rekom.get(2).getNama() + "\n" +
                        rekom.get(3).getNama());
        } else {
            out.setTeks("Maaf tidak ada rekomendasi yang sesuai dengan budget atau selera anda :(");
        }
        } else {
            out.setTeks("Kepala bapakkau");
        }
        out.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void veganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veganActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        int loop = rekom.size();
        int i = 0;        
        while(i <= loop) {
            if(rekom.get(i).getVegan()) {
                i++;
            } else {
                rekom.remove(i);
                loop = rekom.size();
                i = 0; 
            }
            
        }
    }//GEN-LAST:event_veganActionPerformed

    private void manisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manisActionPerformed
        // TODO add your handling code here:
        if(manis.isSelected()) {
            rekom.add(menu.getSpaghetti());
            rekom.add(menu.getRotiDaging());
        }
    }//GEN-LAST:event_manisActionPerformed

    private void asamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asamActionPerformed
        // TODO add your handling code here:
        if(asam.isSelected()) {
            rekom.add(menu.getSpaghetti());
            rekom.add(menu.getNasGor());
            rekom.add(menu.getRotiDaging());
            rekom.add(menu.getKofta());
        }
    }//GEN-LAST:event_asamActionPerformed

    private void asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asinActionPerformed
        // TODO add your handling code here:
        if(asin.isSelected()) {
            rekom.add(menu.getSpaghetti());
        }
    }//GEN-LAST:event_asinActionPerformed

    private void pedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedasActionPerformed
        // TODO add your handling code here:
        if(pedas.isSelected()) {
            rekom.add(menu.getSpaghetti());
            rekom.add(menu.getKofta());
        }
    }//GEN-LAST:event_pedasActionPerformed

    private void gurihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gurihActionPerformed
        // TODO add your handling code here:
        if(gurih.isSelected()) {
            rekom.add(menu.getNasGor());
        }
    }//GEN-LAST:event_gurihActionPerformed

    private void mknMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mknMoneyActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        
        int money = Integer.parseInt(mknMoney.getText());
        int loop = rekom.size();
        int i = 0;
        while(i <= loop) {
            if(money < rekom.get(i).getHarga()) {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            } else {
                i++;
            }
        }
        
    }//GEN-LAST:event_mknMoneyActionPerformed

    private void nonVeganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonVeganActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        int loop = rekom.size();
        int i = 0;
        while(i <= loop) {
            if(rekom.get(i).getVegan()) {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            } else {
                i++;
            }
        }
    }//GEN-LAST:event_nonVeganActionPerformed

    private void healtyFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healtyFActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        int loop = rekom.size();
        int i = 0;
        while(i <= loop) {
            if(rekom.get(i).getHealty()) {
                i++;
            } else {
            rekom.remove(i);
            loop = rekom.size();
            i = 0;
            }
        }
    }//GEN-LAST:event_healtyFActionPerformed

    private void negaraMknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaraMknActionPerformed
        // TODO add your handling code here:
        if(rekom.isEmpty()) {
            addMenuMakan();
        }
        
        if (negaraMkn.getSelectedItem().equals("China")) {
            int loop = rekom.size();
            int i = 0;
            while(i <= loop) {
            if(rekom.get(i).getNegara().equalsIgnoreCase("China")) {
                i++;
            } else {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            }
            }
        } else if (negaraMkn.getSelectedItem().equals("Indonesia")) {
            int loop = rekom.size();
            int i = 0;
            while(i <= loop) {
            if(rekom.get(i).getNegara().equalsIgnoreCase("Indonesia")) {
                i++;
            } else {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            }
            }
        } else if (negaraMkn.getSelectedItem().equals("Italia")) {
            int loop = rekom.size();
            int i = 0;
            while(i <= loop) {
            if(rekom.get(i).getNegara().equalsIgnoreCase("Italia")) {
                i++;
            } else {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            }
            }
        } else if(negaraMkn.getSelectedItem().equals("Mesir")) {
            int loop = rekom.size();
            int i = 0;
            while(i <= loop) {
            if(rekom.get(i).getNegara().equalsIgnoreCase("Mesir")) {
                i++;
            } else {
                rekom.remove(i);
                loop = rekom.size();
                i = 0;
            }
            }
        }
    }//GEN-LAST:event_negaraMknActionPerformed

    private void negaraMnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaraMnumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_negaraMnumActionPerformed

    // Berpindah panel
    private void switchPane(JPanel panel) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
    
    private void addMenuMakan() {
        rekom.add(menu.getSpaghetti());
        rekom.add(menu.getNasGor());
        rekom.add(menu.getRotiDaging());
        rekom.add(menu.getKofta());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asam;
    private javax.swing.JCheckBox asin;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> choose;
    private javax.swing.JCheckBox gurih;
    private javax.swing.JRadioButton healtyF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton junkF;
    private javax.swing.JPanel layerMakanan;
    private javax.swing.JPanel layerMinuman;
    private javax.swing.JCheckBox manis;
    private javax.swing.JTextField mknMoney;
    private javax.swing.JTextField mnumMoney;
    private javax.swing.JComboBox<String> negaraMkn;
    private javax.swing.JComboBox<String> negaraMnum;
    private javax.swing.JRadioButton nonVegan;
    private javax.swing.JCheckBox pedas;
    private javax.swing.ButtonGroup shtMakanan;
    private javax.swing.ButtonGroup sizeMinuman;
    private javax.swing.JRadioButton vegan;
    private javax.swing.ButtonGroup ynEs;
    private javax.swing.ButtonGroup ynKafein;
    private javax.swing.ButtonGroup ynMakanan;
    // End of variables declaration//GEN-END:variables
}
